### ISSUE TITLE
Emby android app sending playback stop twice, only when playing music.

### ISSUE THREAD

**Issue by jaycedk** [TOomaAh/emby_exporter_go#10]
This issue is a bit weird, but when playing music from Emby android app, It looks like the app sends playback stop twice.
That manifests in an error in your exporter like this.

An error has occurred while serving metrics:

collected metric "emby_activity" { label:<name:"date" value:"23/01/2023 16:30:45" > label:<name:"name" value:"User has finished playing 4 Non Blondes - Train on Device" > label:<name:"severity" value:"Info" > label:<name:"type" value:"AudioPlaybackStopped" > gauge:<value:1 > } was collected before with the same name and label values

And now its not exporting anything, before I start and stop 2 music tracks, from a web browser.

Is there anyway we can ignore the last stop message of AudioPlaybackStopped ?

This is a really weird one 😄

**Comment by jaycedk** [comment]
I'm going to copy this issue to Emby forum.
Some one there might have some helpful comments
https://emby.media/community/index.php?/topic/106218-emby-metrics-exporter/

**Comment by TOomaAh** [comment]
Hey !
I will fix this issue quickly 😊

**Comment by jaycedk** [comment]
Great it only looks like its coming from android.
I have not testet it with Android TV, but can test when i'm off work later today.
Web interface and Windows Emby app work as expected :)

**Comment by jaycedk** [comment]
Ok just tested on Android TV.
Its happening on that devise to.

An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric "emby_activity" { label:<name:"date" value:"24/01/2023 15:18:01" > label:<name:"name" value:"User has finished playing Enya - On Your Shore on SHIELD" > label:<name:"severity" value:"Info" > label:<name:"type" value:"AudioPlaybackStopped" > gauge:<value:2 > } was collected before with the same name and label values
* collected metric "emby_activity" { label:<name:"date" value:"24/01/2023 15:14:00" > label:<name:"name" value:"User has finished playing Enya - Cursum Perficio on SHIELD" > label:<name:"severity" value:"Info" > label:<name:"type" value:"AudioPlaybackStopped" > gauge:<value:5 > } was collected before with the same name and label values

And thank you for looking into this 😄

**Comment by jaycedk** [comment]
Hey
Any progress on this issue, just checking in.

**Comment by TOomaAh** [comment]
Sorry for the time it took (the studies....).
The problem is solved

It's build and upload on DockerHub. Can you try a give me a feedback :)

**Comment by jaycedk** [comment]
Thank you for the fix 😄 
It works 👍
