### ISSUE TITLE
Only able to get count of 1 library folder

### ISSUE THREAD

**Issue by Exhabition** [TOomaAh/emby_exporter_go#11]
While having 6 folders with media in them, emby_exporter only returns 1 in the metrics, TV shows. 
![image](https://github.com/TOomaAh/emby_exporter_go/assets/63742759/172023d7-0b23-49df-bf32-ced33d2a1cee)
![image](https://github.com/TOomaAh/emby_exporter_go/assets/63742759/92a71612-950b-4c5e-98b1-5341d794b4f0)

The UserID I passed along is from an admin user, so it should be able to return all libraries right?

**Comment by Exhabition** [comment]
both queries for `GetLibrary` and `GetLibrarySize` return valid results when executed locally with the API key that I also passed along for emby exporter to use:
`/Library/VirtualFolders/Query`
```json
{
    "Items": [
        {
            "Name": "Anime Movies",
            "Locations": [
                "/Media/Anime/Movies"
            ],
            "CollectionType": "movies",
            "LibraryOptions": {
                 ...lib options
            },
            "ItemId": "8",
            "Guid": "...",
            "PrimaryImageItemId": "8",
            "RefreshStatus": "Idle"
        },
        ...and more items
```
Using itemID 8 from the previous query:
`/Users/userid/Items?IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo&EnableImageTypes=Primary&ParentId=8&Limit=1`
```json
{
    "Items": [
        {
            "Name": "5 Centimeters per Second",
            "ServerId": "...",
            "Id": "33078",
            "SupportsSync": true,
            "RunTimeTicks": 37657610000,
            "IsFolder": false,
            "Type": "Movie",
            "UserData": {
                "PlaybackPositionTicks": 0,
                "PlayCount": 0,
                "IsFavorite": false,
                "Played": false
            },
            "ImageTags": {
                "Primary": "..."
            },
            "MediaType": "Video"
        }
    ],
    "TotalRecordCount": 20
}
```

**Comment by TOomaAh** [comment]
> both queries for `GetLibrary` and `GetLibrarySize` return valid results when executed locally with the API key that I also passed along for emby exporter to use: `/Library/VirtualFolders/Query`
> 
> ```json
> {
>     "Items": [
>         {
>             "Name": "Anime Movies",
>             "Locations": [
>                 "/Media/Anime/Movies"
>             ],
>             "CollectionType": "movies",
>             "LibraryOptions": {
>                  ...lib options
>             },
>             "ItemId": "8",
>             "Guid": "...",
>             "PrimaryImageItemId": "8",
>             "RefreshStatus": "Idle"
>         },
>         ...and more items
> ```
> 
> Using itemID 8 from the previous query: `/Users/userid/Items?IncludeItemTypes=Movie&Recursive=true&Fields=BasicSyncInfo&EnableImageTypes=Primary&ParentId=8&Limit=1`
> 
> ```json
> {
>     "Items": [
>         {
>             "Name": "5 Centimeters per Second",
>             "ServerId": "...",
>             "Id": "33078",
>             "SupportsSync": true,
>             "RunTimeTicks": 37657610000,
>             "IsFolder": false,
>             "Type": "Movie",
>             "UserData": {
>                 "PlaybackPositionTicks": 0,
>                 "PlayCount": 0,
>                 "IsFavorite": false,
>                 "Played": false
>             },
>             "ImageTags": {
>                 "Primary": "..."
>             },
>             "MediaType": "Video"
>         }
>     ],
>     "TotalRecordCount": 20
> }
> ```

Hey! So sorry for the wait!
Indeed, I just fixed the problem! Thanks a lot!

**Comment by TOomaAh** [comment]
Let me know if it's all set up on your end!

**Comment by Exhabition** [comment]
> Let me know if it's all set up on your end!

Sorry for the late reply, I just tried this with Docker and I am getting a build error indicating that the go version isn't correct:
![image](https://github.com/TOomaAh/emby_exporter_go/assets/63742759/a04584ff-2a65-4ecb-a968-9d13d03bb218)

**Comment by Exhabition** [comment]
Had to change the go version to at least 1.19 for it to build without errors about the go version, however now there is a COPY command that points to a file that doesn't exist, I assume the Dockerfile hasn't been updated then?

![image](https://github.com/TOomaAh/emby_exporter_go/assets/63742759/814a413b-b233-404d-9c04-10f3ed73269f)

**Comment by TOomaAh** [comment]
Hello,



I'll look for it, but there is currently an image build on the docker hub.

> > Let me know if it's all set up on your end!
> 
> Sorry for the late reply, I just tried this with Docker and I am getting a build error indicating that the go version isn't correct: ![image](https://user-images.githubusercontent.com/63742759/255874224-a04584ff-2a65-4ecb-a968-9d13d03bb218.png)

No, I haven't had time to push the readme with all the instructions for that yet. I've removed the api for retrieving information from an ip address and am now using  [maxmind](https://www.maxmind.com/en/accounts/659568/geoip/downloads)

To build the docker image, you need to download a maxmind database with your own account.

**Comment by Exhabition** [comment]
> I'll look for it, but there is currently an image build on the docker hub.

I see, but that image doesn't match my host platform, so I wanted to build it myself
