### ISSUE TITLE
Time zone defaults to Europe/paris

### ISSUE THREAD

**Issue by jaycedk** [TOomaAh/emby_exporter_go#12]
I have an timezone issue.
I have tried to change timezone at docker start using this env. command
-e TZ=Europe/Copenhagen
But time is still Europe/Paris time.
The below shows that -e TZ="Europe/Paris" is hardcoded in the docker.

docker run
  -d
  --name='emby-exporter'
  --net='host'
  --privileged=true
### -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="JaycedkUnraid"
  -e HOST_CONTAINERNAME="emby-exporter"
  -e 'CONFIG_FILE'='/config/file.yml'
  -e 'TCP_PORT_9210'='9210'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://github.com/TOomaAh/emby_exporter_go'
  -l net.unraid.docker.icon='https://th.bing.com/th/id/OIP.3kuPLBYGPMHeo7sbMAphzwHaHa?pid=ImgDet&rs=1'
  -v '/mnt/user/appdata/embyexporter/':'/config/':'rw'
###   -e TZ="Europe/Copenhagen" 'bagul/goemby_exporter:latest'
  -e CONFIG_FILE=file.yml

This also shows an offset in Streaming info in grafana, where time is off by 2 hours

Is there anyway to change this behavior ?
Thanks in advance 😀

**Comment by TOomaAh** [comment]
> I have an timezone issue. I have tried to change timezone at docker start using this env. command -e TZ=Europe/Copenhagen But time is still Europe/Paris time. The below shows that -e TZ="Europe/Paris" is hardcoded in the docker.
> 
> docker run -d --name='emby-exporter' --net='host' --privileged=true
> 
> ### -e TZ="Europe/Paris"
> -e HOST_OS="Unraid" -e HOST_HOSTNAME="JaycedkUnraid" -e HOST_CONTAINERNAME="emby-exporter" -e 'CONFIG_FILE'='/config/file.yml' -e 'TCP_PORT_9210'='9210' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='https://github.com/TOomaAh/emby_exporter_go' -l net.unraid.docker.icon='https://th.bing.com/th/id/OIP.3kuPLBYGPMHeo7sbMAphzwHaHa?pid=ImgDet&rs=1' -v '/mnt/user/appdata/embyexporter/':'/config/':'rw'
> 
> ### -e TZ="Europe/Copenhagen" 'bagul/goemby_exporter:latest'
> -e CONFIG_FILE=file.yml
> 
> This also shows an offset in Streaming info in grafana, where time is off by 2 hours
> 
> Is there anyway to change this behavior ? Thanks in advance 😀

Hello,

Sorry for the late reply.

Does the time displayed in grafana differ from the time displayed on the emby dashboard?

**Comment by jaycedk** [comment]
Yes right now its off by 2 hours, do to summer.
In 2 month its off by 1 hour.

**Comment by jaycedk** [comment]
This is Emby Server Ativity 
![image](https://github.com/TOomaAh/emby_exporter_go/assets/17232146/f0f14483-5cfa-4989-abe6-d38c6cca87e7)
And what I see in Grafana
![image](https://github.com/TOomaAh/emby_exporter_go/assets/17232146/07434ce7-1ef0-4464-863b-7d546cd585bf)
This indicates Europe/Paris time where my time is Europe/Copenhagen

**Comment by TOomaAh** [comment]
API:
![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/5f6c7cfc-6477-47e3-bfc8-52d17eaefefc)

Dashboard:
![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/e38ca7d9-382d-445b-895a-cebb1e996131)


Emby doesn't return the right date, I'll correct it.

**Comment by jaycedk** [comment]
Ohh nice if that is the fix 😁
Ty for looking into this 👍

**Comment by TOomaAh** [comment]
> Ohh nice if that is the fix 😁 Ty for looking into this 👍

It's fixed, the docker image has been published, let me know if it fixes the problem on your side.

**Comment by jaycedk** [comment]
Can you push it to latest, too 😄

**Comment by TOomaAh** [comment]
Done. Sorry. 😄

**Comment by jaycedk** [comment]
He he Nice, will test it in 5 min.

**Comment by jaycedk** [comment]
That did it 👏 
Nice thank you for the fix 👍
