### ISSUE TITLE
Wrong labeling of Direct Play and Direct Stream

### ISSUE THREAD

**Issue by cochize66** [TOomaAh/emby_exporter_go#13]
Hi, yesterday on Emby forum we came to a conslusion that the exporter is giving wrong names for play method. What is Direct Play on Emby dashboard is Direct Stream in Grafana Dashboard and what is Direct Stream seems to be a Transcoding (I assume Transcoding is still Transcoding). Could you please verify that? Pictures attached and emby forum link below:
https://emby.media/community/index.php?/topic/121493-emby-never-direct-playing-any-media-on-any-client/

![Bez tytułu](https://github.com/TOomaAh/emby_exporter_go/assets/118779105/cfdd7942-10cd-49e5-9518-aa56468b35cc)
![image thumb png 1040e0b100090f6149e60062f1433e09](https://github.com/TOomaAh/emby_exporter_go/assets/118779105/462bc785-dcbe-42fa-ad59-c5bd42705643)
![image png c21dafa140e2fc23734f8d1325b401bb](https://github.com/TOomaAh/emby_exporter_go/assets/118779105/b5d543b7-6325-4cb0-ab57-adc74b23c3a7)

**Comment by TOomaAh** [comment]
Hello,

The video playback status that the exporter returns is the status that the Emby api returns. I'm just transmitting the data without modifying it for the status.

I'll see if I can be more precise and solve this.

**Comment by TOomaAh** [comment]
Hello, 

following the conversation on the emby forum thread, I decided to do it this way:

1. If none of the streams (video or audio) are modified and the API returns DirectStream then I return "Direct Play".
2. If none of the streams are modified but the API returns "Transcoding", I return "Transcoding" + the reason for transcoding.
3. If one of the streams is modified, then the same as above. I return "Transcoding" + the reason for transcoding.
4. If the API ever returns DirectPlay, I return "Direct Play", of course.

**Comment by TOomaAh** [comment]
Hey,
This is what it looks like. If there are several reasons, they will be displayed separated by a comma.

I'll add the video bitrate to this release and later in another version I'll add the CPU usage in a new metric. 

![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/39ece9c3-e218-4f50-ba7a-59d53b2c2638)

**Comment by cochize66** [comment]
Awesomem and by any chence is it also possible to add the actuall length of the movie/series not just percent (or maybe it is now and I am missing someting)? Also is it possible to no. of the episode next to the Episode in Type field? 
![Bez tytułu](https://github.com/TOomaAh/emby_exporter_go/assets/118779105/353caccf-7cc8-4aee-8e99-6485969f5040)

**Comment by TOomaAh** [comment]
Oh! Did you build the docker image?
Yes, it's a great idea! I'll change the name of the element when it's an episode to "Ep. X - Name" or I'll make a new field.

**Comment by cochize66** [comment]
Yeah, I run your exporter in docker but I wouldn't call it 'biilding' it:) Episode no. would be great with added X value in the same field since the same column also shows the Movie value. And what about the actual time of the media, is that possible?

**Comment by TOomaAh** [comment]
Yes, I'll add the episode number and media duration in the next release.

**Comment by TOomaAh** [comment]
I've added the episode duration and episode number if available.
I'm still checking and testing a few things and I'm finishing the automatic deployment of the Docker container on different architectures and I'm publishing the release that it's all done.

![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/4c9e9d95-024e-4db2-8a31-28ddce437b19)

**Comment by cochize66** [comment]
Duration will also be available for movies of course, right?:) And will there be an option to show current state played or it will have to be calculated from media duration and percent played?

**Comment by TOomaAh** [comment]
Of course, the duration is displayed for all media.

I don't understand what you want. Do you want to know if the media is marked as read or not?

**Comment by cochize66** [comment]
I wanto to know the current state of media played, same as percent but in minutes, example: 1h episode, right now after 30 min we see 50% played and is it possible to say 30 min played (I have my grafana dashboard refreshing every 2 sec so it would be almost as an Emby dashboard

**Comment by TOomaAh** [comment]
Ah you want the elapsed time of a video playback.
Ok I get it. Yes I can add this metric.

**Comment by TOomaAh** [comment]
I've pushed a docker image with the dev tag on several platforms if you want to try to see if it works correctly.

![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/e9061552-5b48-439c-a9e1-e0dec46f935c)

**Comment by jaycedk** [comment]
@TOomaAh  I have just tried you dev build.
👍😁😎🤓

**Comment by jaycedk** [comment]
![image](https://github.com/TOomaAh/emby_exporter_go/assets/17232146/1f5a5d7e-5230-4235-9a77-b15b39df0fde)

**Comment by jaycedk** [comment]
Screen shoot of emby
![image](https://github.com/TOomaAh/emby_exporter_go/assets/17232146/fb135721-1015-4284-a0f1-298283a44701)

**Comment by cochize66** [comment]
Hi, a quick question. I want to update the exporter to dev image but don't want to lose historical data gathered so far. I hava a docker image with only config.yml file mapped outside the root Synology folder so when I update it it will be wiped out. Below is my docker compose. How can I find and maybe copy and map for the future updates my currect database?
`goemby_exporter:
        container_name: emby_exporter
        environment:
            - CONFIG_FILE=/config/config.yml
            - TZ=Europe/Warsaw
        volumes:
            - '/volume1/docker/embyexporter/config:/config'
        ports:
            - '9210:9210'
        image: 'bagul/goemby_exporter:latest'
        networks:
            - emby_net
        restart: always`

**Comment by TOomaAh** [comment]
> Hi, a quick question. I want to update the exporter to dev image but don't want to lose historical data gathered so far. I hava a docker image with only config.yml file mapped outside the root Synology folder so when I update it it will be wiped out. Below is my docker compose. How can I find and maybe copy and map for the future updates my currect database? `goemby_exporter: container_name: emby_exporter environment: - CONFIG_FILE=/config/config.yml - TZ=Europe/Warsaw volumes: - '/volume1/docker/embyexporter/config:/config' ports: - '9210:9210' image: 'bagul/goemby_exporter:latest' networks: - emby_net restart: always`

You don't have to be on the dev branch because it may contain bugs (which will be corrected even if it's better to have testers ahah).
But normally my image only exports the information that prometheus keeps on its side (normally you've mapped a data folder for prometheus) see: https://prometheus.io/docs/prometheus/1.8/storage/

**Comment by cochize66** [comment]
Got convinced on the very first phrase: "Prometheus has a sophisticated local storage subsystem." :)

**Comment by jaycedk** [comment]
I think we can close this 😀
Can you push it to latest on docker hub, please.
I'm current on dev, but would rather be on latest.

**Comment by TOomaAh** [comment]
![image](https://github.com/TOomaAh/emby_exporter_go/assets/28620362/5c7a661a-8fa9-43fc-b24d-be3254c2fca4)

Available now

**Comment by jaycedk** [comment]
Thank you 😀
