### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by cochize66** [TOomaAh/emby_exporter_go#28]
Hi, since couple of hours I am noticing a strange error and no metrics are being displayed, any idea what could that be?
"
An error has occurred while serving metrics:

collected metric "emby_media_item" { label:{name:"name" value:"Recordings"} gauge:{value:0}} was collected before with the same name and label values
"

**Comment by TOomaAh** [comment]
> Hi, since couple of hours I am noticing a strange error and no metrics are being displayed, any idea what could that be? " An error has occurred while serving metrics:
> 
> collected metric "emby_media_item" { label:{name:"name" value:"Recordings"} gauge:{value:0}} was collected before with the same name and label values "

Hello,

You seem to have several libraries with the same name (Recording) with 0 elements.

I solve this problem

**Comment by TOomaAh** [comment]
> Hi, since couple of hours I am noticing a strange error and no metrics are being displayed, any idea what could that be? " An error has occurred while serving metrics:
> 
> collected metric "emby_media_item" { label:{name:"name" value:"Recordings"} gauge:{value:0}} was collected before with the same name and label values "

Problem solved with version 1.0.10
