### ISSUE TITLE
Make geoip optional

### ISSUE THREAD

**Issue by Dual-0** [TOomaAh/emby_exporter_go#3]
Hi,

first of all: thanks a lot for this great exporter! Works very good for me.

my request: is it possible to make the geoip function optional? I don't need it and it would be good for people who don't want to send their data to ip-api.com.

Thanks in advance

**Comment by TOomaAh** [comment]
Hey! Yes I can make this optional via the configuration file and this is a very good idea indeed.

But I have to find an alternative with SSL support anyway I thought I would disable this the time. Or use GeoLite2 (MaxMind) which provides a database

**Comment by TOomaAh** [comment]
Here is the new option for the configuration file.

```
options: # optional
  geoip: true # optional : default false
```
