### ISSUE TITLE
bitrates metric

### ISSUE THREAD

**Issue by ZombieApps** [TOomaAh/emby_exporter_go#32]
Hi, thanks for a very useful project

In addition to graphing the usual things I also wanted to graph the bandwidth consumed by each user, via the "bitrate" label in emby_sessions

But it appears that Grafana isn't able to create a time-series graph from a label, only from the main metric value.

So I [modified session.go to add another "emby_sessions_bitrate" metric](https://github.com/TOomaAh/emby_exporter_go/compare/main...ZombieApps:emby_exporter_go:bitrate?expand=1)
 
![embygrafana](https://github.com/user-attachments/assets/bea6786c-ab8f-4a03-ae0c-a21be45f6755)

Please let me know if I've gone down the right path, and I'll send through a pull request.

Otherwise let me know a better way to handle this.

**Comment by TOomaAh** [comment]
Hello,
Sorry for the delay.
I'll add the metrics. But on the PR that you propose there is a possibility of error if a person looks at an element with the same bitrate.

**Comment by TOomaAh** [comment]
> Hi, thanks for a very useful project
> 
> In addition to graphing the usual things I also wanted to graph the bandwidth consumed by each user, via the "bitrate" label in emby_sessions
> 
> But it appears that Grafana isn't able to create a time-series graph from a label, only from the main metric value.
> 
> So I [modified session.go to add another "emby_sessions_bitrate" metric](https://github.com/TOomaAh/emby_exporter_go/compare/main...ZombieApps:emby_exporter_go:bitrate?expand=1)
> 
> ![embygrafana](https://private-user-images.githubusercontent.com/174158372/356130820-bea6786c-ab8f-4a03-ae0c-a21be45f6755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzY0NzgsIm5iZiI6MTcyMzczNjE3OCwicGF0aCI6Ii8xNzQxNTgzNzIvMzU2MTMwODIwLWJlYTY3ODZjLWFiOGYtNGEwMy1hZTBjLWEyMWJlNDVmNjc1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNTM2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmJkNTNlNTU4N2YwMjgwYjUxYjQ1MDhlOWVjNzBiNjFmNTYyNDhjZTU0NTY2ZjU1ZmJmZDE3ZWUzNDI1NWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AK3zjt1L9YTppKRc86z3HPXVEp-p-c6NMjSSdF8W8Vw)
> 
> Please let me know if I've gone down the right path, and I'll send through a pull request.
> 
> Otherwise let me know a better way to handle this.

The metric has been added in version 1.0.11 and is in Kilobytes.

**Comment by ZombieApps** [comment]
> The metric has been added in version 1.0.11 and is in Kilobytes.

Thanks!

FYI the bitrate reported by emby is in bits, not bytes.  So the new metric now reports in kilobits.

And for grafana bits is preferred over kilobits because it will then automatically scale the graphs appropriately.
Just set _Standard Options -> Unit_ to _Bits (SI)_ and it will automatically change the axis to Kb or Mb

![bitrate](https://github.com/user-attachments/assets/fb109276-feb7-4d16-87a7-9fd49d4965eb)

I've now changed my grafana to multiply by 1024 again so that this works correctly.

My Emby server's internet (outbound) is limited to around 45Mb which is why I keep a close eye on this.

**Comment by TOomaAh** [comment]
> > The metric has been added in version 1.0.11 and is in Kilobytes.
> 
> 
> 
> Thanks!
> 
> 
> 
> FYI the bitrate reported by emby is in bits, not bytes.  So the new metric now reports in kilobits.
> 
> 
> 
> And for grafana bits is preferred over kilobits because it will then automatically scale the graphs appropriately.
> 
> Just set _Standard Options -> Unit_ to _Bits (SI)_ and it will automatically change the axis to Kb or Mb
> 
> 
> 
> ![bitrate](https://github.com/user-attachments/assets/fb109276-feb7-4d16-87a7-9fd49d4965eb)
> 
> 
> 
> I've now changed my grafana to multiply by 1024 again so that this works correctly.
> 
> 
> 
> My Emby server's internet (outbound) is limited to around 45Mb which is why I keep a close eye on this.
> 
> 
> 
> 
> 
> 
> 
> 

You're right! I'm displaying kilobits.
The error is also present on sessions, I'll fix it in the next version.

(This will only affect the unit and description. Not the values currently returned.)

**Comment by jaycedk** [comment]
@ZombieApps would you share that graph ?
I like it but can't get it looking like yours 😂

**Comment by ZombieApps** [comment]
> @ZombieApps would you share that graph ?

```json
{
  "datasource": {
    "type": "prometheus",
    "uid": "bdspr5ljopm2od"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "bars",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "insertNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "normal",
          "group": "A"
        },
        "axisPlacement": "left",
        "axisLabel": "",
        "axisColorMode": "text",
        "axisBorderShow": false,
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisSoftMax": 45000000,
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 3
          },
          {
            "color": "red",
            "value": 5
          }
        ]
      },
      "decimals": 1,
      "unit": "decbits"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Total"
        },
        "properties": [
          {
            "id": "custom.stacking",
            "value": {
              "group": "A",
              "mode": "none"
            }
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": false,
              "tooltip": true,
              "viz": true
            }
          },
          {
            "id": "color",
            "value": {
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byFrameRefID",
          "options": "A"
        },
        "properties": [
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": true,
              "tooltip": false,
              "viz": false
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Value"
        },
        "properties": []
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Streams"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "mode": "fixed"
            }
          },
          {
            "id": "unit",
            "value": "none"
          },
          {
            "id": "decimals",
            "value": 0
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": false,
              "tooltip": true,
              "viz": true
            }
          },
          {
            "id": "custom.axisPlacement",
            "value": "left"
          }
        ]
      },
      {
        "matcher": {
          "id": "byFrameRefID",
          "options": "D"
        },
        "properties": [
          {
            "id": "custom.axisPlacement",
            "value": "hidden"
          },
          {
            "id": "custom.drawStyle",
            "value": "line"
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": true,
              "tooltip": false,
              "viz": false
            }
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "#808080",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 6,
    "w": 24,
    "x": 0,
    "y": 10
  },
  "id": 27,
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "table",
      "placement": "right",
      "calcs": [
        "max",
        "last"
      ],
      "width": 220
    }
  },
  "pluginVersion": "11.1.3",
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "bdspr5ljopm2od"
      },
      "disableTextWrap": false,
      "editorMode": "code",
      "exemplar": false,
      "expr": "sum by(username) (emby_sessions_bitrate{username!=\"zombie\"}) * 1024",
      "format": "time_series",
      "fullMetaSearch": false,
      "includeNullMetadata": true,
      "instant": false,
      "legendFormat": "{{username}}",
      "range": true,
      "refId": "A",
      "useBackend": false
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "bdspr5ljopm2od"
      },
      "disableTextWrap": false,
      "editorMode": "code",
      "exemplar": false,
      "expr": "sum(emby_sessions_bitrate{username!=\"zombie\"}) * 1024 or vector(0)",
      "fullMetaSearch": false,
      "hide": false,
      "includeNullMetadata": true,
      "instant": false,
      "interval": "",
      "legendFormat": "Total",
      "range": true,
      "refId": "B",
      "useBackend": false
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "bdspr5ljopm2od"
      },
      "editorMode": "code",
      "expr": "emby_sessions_count",
      "hide": false,
      "instant": false,
      "legendFormat": "Streams",
      "range": true,
      "refId": "C"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "bdspr5ljopm2od"
      },
      "editorMode": "code",
      "expr": "sum by(username) (emby_sessions_bitrate{username=\"zombie\"}) * 1024",
      "hide": false,
      "instant": false,
      "legendFormat": "zombie",
      "range": true,
      "refId": "D"
    }
  ],
  "title": "Bitrate per stream",
  "type": "timeseries"
}
```

I run two sets of queries, because I'm local to the server, 
That means I don't need to stack my bandwidth on top of the others, instead it's drawn as a line graph on top of the blocks.

![bitrates](https://github.com/user-attachments/assets/dbd59c1b-66a3-4497-9990-d56b794e0314)

You can delete queries C and D and remove the label filters if you want everything grouped together

**Comment by jaycedk** [comment]
Thank you 👍
