### ISSUE TITLE
library size as value

### ISSUE THREAD

**Issue by Dual-0** [TOomaAh/emby_exporter_go#4]
Hi,

I think [it would be better](https://www.robustperception.io/cardinality-is-key/) to return the library size `emby_media_item` as a value instead of a label.

Also the `emby_system_info` metric should return the version number instead of value "1"

regards
Dual-0

**Comment by TOomaAh** [comment]
Hey! I do indeed take care of that. I still have some optimization to do.

**Comment by TOomaAh** [comment]
> I think [it would be better](https://www.robustperception.io/cardinality-is-key/) to return the library size `emby_media_item` as a value instead of a label.

The number of media is well defined as a value.



> Also the `emby_system_info` metric should return the version number instead of value "1"

I'm not sure I can do that. I can return the major version of Emby (e.g. 4.7) but I can't return the exact version (e.g. 4.7.6.0)
