### ISSUE TITLE
An error has occurred while serving metrics

### ISSUE THREAD

**Issue by fanek007** [TOomaAh/emby_exporter_go#5]
Hello,

First of all, thank you for this project.
I want to use the Emby exporter on Windows 10, but once I try to retrieve metrics, I get this error:

#################################
An error has occurred while serving metrics:

collected metric "emby_alert" { label:<name:"date" value:"31/07/2022 14:09:40" > label:<name:"name" value:"A new camera image has been uploaded to Media Server from ..." > label:<name:"overview" value:"" > label:<name:"severity" value:"Info" > label:<name:"shortOverview" value:"" > label:<name:"type" value:"CameraImageUploaded" > gauge:<value:3 > } was collected before with the same name and label values
#################################

Thank you,
Fanek

**Comment by TOomaAh** [comment]
Hey! Thanks for the feedback. I'm looking into this very quickly!

**Comment by TOomaAh** [comment]
I have so far worked around the problem. Normally you won't get the error anymore.

I definitely fix the problem as soon as I have more time.

**Comment by fanek007** [comment]
Hey, thank you for your answer. I downloaded the latest version (1.0.2) and, unfortunately, still getting the same error:

#################################
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric "emby_alert" { label:<name:"date" value:"14/08/2022 18:28:13" > label:<name:"name" value:"A new camera image has been uploaded to Media Server from ..." > label:<name:"overview" value:"" > label:<name:"severity" value:"Info" > label:<name:"shortOverview" value:"" > label:<name:"type" value:"CameraImageUploaded" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "emby_alert" { label:<name:"date" value:"14/08/2022 18:28:13" > label:<name:"name" value:"A new camera image has been uploaded to Media Server from ..." > label:<name:"overview" value:"" > label:<name:"severity" value:"Info" > label:<name:"shortOverview" value:"" > label:<name:"type" value:"CameraImageUploaded" > gauge:<value:2 > } was collected before with the same name and label values
* collected metric "emby_alert" { label:<name:"date" value:"14/08/2022 18:28:13" > label:<name:"name" value:"A new camera image has been uploaded to Media Server from ..." > label:<name:"overview" value:"" > label:<name:"severity" value:"Info" > label:<name:"shortOverview" value:"" > label:<name:"type" value:"CameraImageUploaded" > gauge:<value:3 > } was collected before with the same name and label values
#################################

**Comment by TOomaAh** [comment]
Hey! Sorry for the wait!

I solved the problem, the alerts in your case could be completely identical.

I solved the problem by adding the id in the information.
