### ISSUE TITLE
Media counter is at 0

### ISSUE THREAD

**Issue by krptg0** [TOomaAh/emby_exporter_go#6]
Hi,

Media counter is set to 0, doesn't take into accounts my libraries it seems : 

```
# HELP emby_media_item All Media Item
# TYPE emby_media_item gauge
emby_media_item{name="Collections"} 0
emby_media_item{name="Movies"} 0
emby_media_item{name="Playlists"} 0
emby_media_item{name="TV shows"} 0
# HELP emby_sessions_count Session Count
# TYPE emby_sessions_count gauge
emby_sessions_count 0
# HELP emby_system_info All Emby Info
# TYPE emby_system_info gauge
```

Thanks :)

EDIT: Also, can you share your grafana dashboard ?

**Comment by TOomaAh** [comment]
Hey!
I'm going to add some logs because if the size is 0 it's an error I think.

For the dashboard I will share it :)

**Comment by TOomaAh** [comment]
> Hi,
> 
> Media counter is set to 0, doesn't take into accounts my libraries it seems :
> 
> ```
> # HELP emby_media_item All Media Item
> # TYPE emby_media_item gauge
> emby_media_item{name="Collections"} 0
> emby_media_item{name="Movies"} 0
> emby_media_item{name="Playlists"} 0
> emby_media_item{name="TV shows"} 0
> # HELP emby_sessions_count Session Count
> # TYPE emby_sessions_count gauge
> emby_sessions_count 0
> # HELP emby_system_info All Emby Info
> # TYPE emby_system_info gauge
> ```
> 
> Thanks :)
> 
> EDIT: Also, can you share your grafana dashboard ?

Hey! I just added logs could you copy the logs (if there are any) that will be displayed in the console.

**Comment by krptg0** [comment]
Hey @TOomaAh , there you go :)
```
2022/08/12 07:38:29 Beginning to serve on port 9210
2022/08/12 07:38:31 Emby Server - GetLibrarySize : invalid character 'I' looking for beginning of value
2022/08/12 07:38:31 Emby Server - GetLibrarySize : invalid character 'I' looking for beginning of value
2022/08/12 07:38:31 Emby Server - GetLibrarySize : invalid character 'I' looking for beginning of value
2022/08/12 07:38:31 Emby Server - GetLibrarySize : invalid character 'I' looking for beginning of value
```

**Comment by TOomaAh** [comment]
Hey @krptg0  thanks for your feedback!

The JSON that is returned by your server is not correct. 
I just added more log information. If you can update the exporter and share the new logs.

**Comment by lgromb** [comment]
And here's the updated logs :

```
022/08/12 09:29:48 Beginning to serve on port 9210
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
```

**Comment by krptg0** [comment]
And here's the updated logs :

```
022/08/12 09:29:48 Beginning to serve on port 9210
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:54 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : invalid character 'I' looking for beginning of value
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : syntax error at byte offset 1
2022/08/12 09:29:55 Emby Server - GetLibrarySize Unmarshal : response body => "Input string was not in a correct format."
```

**Comment by TOomaAh** [comment]
Hello,

I managed to reproduce your problem by putting a wrong user id. Is your user id good? Do you have access to these libraries?

**Comment by krptg0** [comment]
Hey @TOomaAh, pretty sure I do have access to those libraries, but I think maybe I don't have the same library names as you. Is it hardcoded ? These are the 2 I want to monitor :
![image](https://user-images.githubusercontent.com/45569465/184809289-24e5e865-0abf-4870-ab22-f8084d6e3002.png)

Thanks :)

**Comment by TOomaAh** [comment]
@krptg0 

No, the library names are not hardcoded.

Is your UserID good in the configuration file?

Here is what it gives me, I added only one series and one movie but the number of items appears well.

![image](https://user-images.githubusercontent.com/28620362/184856672-41bc8980-9fb7-48da-9df3-c760e37b550c.png)

![image](https://user-images.githubusercontent.com/28620362/184857363-b5f04ca2-0798-407b-863c-f9eb2604d90e.png)

**Comment by krptg0** [comment]
Nevermind, I thought the UserID was the username...
I got the proper ID and now everything works !

Perharps you could update the README to explain how to get the userID ? :)

Sorry about this issue

**Comment by TOomaAh** [comment]
> Nevermind, I thought the UserID was the username...
> 
> I got the proper ID and now everything works !
> 
> 
> 
> Perharps you could update the README to explain how to get the userID ? :)
> 
> 
> 
> Sorry about this issue

Indeed I will make the change :)

Thanks for your feedback!

**Comment by krptg0** [comment]
@TOomaAh 
Thank you :) I'm eagerly waiting for your dashboard (Having trouble mapping values in the Table panel...)

**Comment by TOomaAh** [comment]
@krptg0 
You can find it in the 'example' folder
