### ISSUE TITLE
Docker shutting down when prometheus tries to connect

### ISSUE THREAD

**Issue by jaycedk** [TOomaAh/emby_exporter_go#9]
Hi strange problem.
Trying to run this exporter on a Unraid server.

The export docker is running fine, until l start up prometheus.
Then the exporter stoppes.
I have also tried connecting to http://ip:9210
That also shuts down the exporter.

Here are the logs from when this happens.

2023/01/14 13:44:44 Beginning to serve on port 9210
2023/01/14 13:44:54 GetServerInfo : invalid character 'A' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8347cb]

goroutine 6 [running]:
TOomaAh/emby_exporter_go/metrics.(*EmbyCollector).Collect(0xc0000cf0c0, 0xc000072060)
        /app/metrics/emby_collector.go:43 +0x4b
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x12b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x5ce

**Comment by TOomaAh** [comment]
> Hi strange problem. Trying to run this exporter on a Unraid server.
> 
> The export docker is running fine, until l start up prometheus. Then the exporter stoppes. I have also tried connecting to http://ip:9210 That also shuts down the exporter.
> 
> Here are the logs from when this happens.
> 
> 2023/01/14 13:44:44 Beginning to serve on port 9210 2023/01/14 13:44:54 GetServerInfo : invalid character 'A' looking for beginning of value panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8347cb]
> 
> goroutine 6 [running]: TOomaAh/emby_exporter_go/metrics.(*EmbyCollector).Collect(0xc0000cf0c0, 0xc000072060) /app/metrics/emby_collector.go:43 +0x4b github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1() /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x12b created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x5ce

It is possible that the error comes from the configuration.
Does your configuration correspond to the one on the readme? https://github.com/TOomaAh/emby_exporter_go#config-file-example

**Comment by jaycedk** [comment]
Hmm might be
Should the user id be admin id or any user.
Right now its set to admin
Here is my config.yml
`server:
    url: "http://192.168.1.4"
    port: 8096
    token: "my token"
    userID: "my userid"
options: # optional
    geoip: true # optional : default false`

**Comment by jaycedk** [comment]
Here is my prometheus config
'  - job_name: 'embyexporter'
  
    scrape_interval: 15s
    
    static_configs:
'      - targets: ["192.168.1.4:9210"]

**Comment by TOomaAh** [comment]
> Here is my prometheus config ' - job_name: 'embyexporter'
> 
> ```
> scrape_interval: 15s
> 
> static_configs:
> ```
> 
> ' - targets: ["192.168.1.4:9210"]

The configuration is good for prometheus.



> Hmm might be Should the user id be admin id or any user. Right now its set to admin Here is my config.yml `server: url: "http://192.168.1.4" port: 8096 token: "my token" userID: "my userid" options: # optional geoip: true # optional : default false`

For the token, it's a stupid question but you have generated it from "Emby settings > Api keys ?
For the UserID I have never tried with a non-admin user but I think it must be admin

Is the indentation of the config file the same as on the readme?

**Comment by jaycedk** [comment]
Hmm wait a min.
Think i used the server id.
Is the token the api key ? that i can generate.
Then I will test that.

**Comment by TOomaAh** [comment]
> Hmm wait a min. Think i used the server id. Is the token the api key ? that i can generate. Then I will test that.

Yes the token is an api key. I will clarify this in the readme.

**Comment by jaycedk** [comment]
Ohh f&%k me, that was a stupid mistake on my side.
Token = API key.
🤦‍♂️
Thanks for all your help 😁

**Comment by TOomaAh** [comment]
> Ohh f&%k me, that was a stupid mistake on my side. Token = API key. 🤦‍♂️ Thanks for all your help 😁

Perfect Ahah.
I'll change the readme to make it clearer.

**Comment by jaycedk** [comment]
You can close this issue.
Well not an Issue, just me being dumb 🙄
